name: CD

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    permissions:
      contents: write
    uses: jeffersonlab/java-workflows/.github/workflows/gh-release.yaml@v2
    with:
      files: build/libs/resize.war
    secrets: inherit

  # COMMENTED OUT BECAUSE OF ISSUE #4
  #docker_publish:
  #  permissions:
  #    contents: read
  #  needs:
  #    - release
  #  uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yaml@v2
  #  with:
  #    semvertag: ${{ needs.release.outputs.semvertag }}
  #  secrets: inherit

  acctest_deploy:
    permissions:
      contents: read
    needs:
      - release
    uses: jeffersonlab/general-workflows/.github/workflows/jlab-deploy-app.yaml@v2
    with:
      app: resize
      env: acctest
      ver: ${{ needs.release.outputs.semver }}
    secrets: inherit